const documents = [
  {id:1,shortTitle:'Gestión Forestal',title:'Catálogo de Objetos de Gestión Forestal del Departamento de Ucayali',category:'Catálogos',badge:'CATÁLOGO TÉCNICO',year:'Versión 1.0',description:'Documento técnico para la organización y estandarización de objetos geográficos vinculados a la gestión forestal de Ucayali. El visor reproduce las 97 páginas originales en formato libro.',institution:'Gobierno Regional de Ucayali',type:'Catálogo de objetos geográficos',scope:'Departamento de Ucayali',reference:'Gestión forestal · ISO 19110',tags:['Gestión forestal','Objetos geográficos','Estandarización','Interoperabilidad'],previewType:'PDF local · 97 páginas',pdf:'documentos/CATALOGO DE OBJETOS FORESTALES UCAYALI.pdf',pagesFolder:'paginas/forestal',pageCount:97,cover:'paginas/forestal/001.jpg',gradient:'linear-gradient(150deg,#1f6f50,#8eaa58)'},
  {id:2,shortTitle:'Comunidades Nativas',title:'Catálogo de Objetos y Símbolos Geográficos de Comunidades Nativas del Departamento de Ucayali',category:'Catálogos',badge:'CATÁLOGO TÉCNICO',year:'Versión 1.0 · 2017',description:'Catálogo orientado a normalizar la información espacial relacionada con comunidades nativas, reconocimiento, titulación y representación cartográfica. El visor reproduce las 68 páginas originales.',institution:'Gobierno Regional de Ucayali · Dirección Regional de Agricultura',type:'Catálogo de objetos y símbolos geográficos',scope:'Comunidades nativas de Ucayali',reference:'NTP-ISO 19110 · NTP-ISO 19117',tags:['Comunidades nativas','Territorio','Catálogo','Datos espaciales'],previewType:'PDF local · 68 páginas',pdf:'documentos/CATALOGO CCNN UCAYALI.pdf',pagesFolder:'paginas/ccnn',pageCount:68,cover:'paginas/ccnn/001.jpg',gradient:'linear-gradient(150deg,#8e6a25,#d0a33b)'},
  {id:3,shortTitle:'Mapa Base',title:'Catálogo de Objetos Geográficos del Mapa Base del Departamento de Ucayali',category:'Catálogos',badge:'CATÁLOGO TÉCNICO',year:'1ra. versión',description:'Documento de referencia para la estandarización de objetos fundamentales del mapa base regional: circunscripción político-administrativa, hidrografía, transportes, relieve y puntos de control. El visor reproduce las 69 páginas originales.',institution:'Gobierno Regional de Ucayali',type:'Catálogo de objetos geográficos',scope:'Mapa base regional',reference:'ISO 19110 · Cartografía base',tags:['Mapa base','Hidrografía','Transportes','Límites'],previewType:'PDF local · 69 páginas',pdf:'documentos/CATALOGO MAPA BASE UCAYALI.pdf',pagesFolder:'paginas/mapa_base',pageCount:69,cover:'paginas/mapa_base/001.jpg',gradient:'linear-gradient(150deg,#3d6b70,#7cae76)'},
  {id:4,shortTitle:'RER N.° 645-2023',title:'Resolución Ejecutiva Regional N.° 645-2023-GRU-GR',category:'Normativa',badge:'GOBERNANZA DE LA IDE',year:'2023',description:'Instrumento normativo regional relacionado con la organización y gobernanza de la Infraestructura de Datos Espaciales de Ucayali.',institution:'Gobierno Regional de Ucayali',type:'Resolución Ejecutiva Regional',scope:'Infraestructura de Datos Espaciales',reference:'N.° 645-2023-GRU-GR',tags:['IDE Ucayali','Gobernanza','Comité de Gestión','Normativa'],previewType:'Página normativa · gob.pe',url:'https://www.gob.pe/institucion/regionucayali/normas-legales/4985178-645-2023-gru-gr',gradient:'linear-gradient(150deg,#5f5449,#b38c52)'},
  {id:5,shortTitle:'Protocolo SERFOR – GOREU',title:'Protocolo para el Intercambio de Información Geográfica entre SERFOR y el Gobierno Regional de Ucayali',category:'Interoperabilidad',badge:'INTEROPERABILIDAD',year:'2023',description:'Protocolo que establece mecanismos para el intercambio de información geográfica mediante la interoperabilidad de bases de datos entre SERFOR y el Gobierno Regional de Ucayali.',institution:'SERFOR · Gobierno Regional de Ucayali',type:'Protocolo interinstitucional',scope:'Intercambio de información geográfica',reference:'Interoperabilidad de bases de datos',tags:['SERFOR','GORE Ucayali','Interoperabilidad','Servicios geográficos'],previewType:'PDF · Protocolo',url:'https://ider.regionucayali.gob.pe/data/mapas/PROTOCOLO%20PARA%20EL%20INTERCAMBIO%20DE%20INFORMACION%20GEOGRAFICA,%20A%20TRAVES%20DE%20LA%20INTEROPERABILIDAD%20DE%20LAS%20BASES%20DE%20DATOS%20ENTRE%20EL%20SERVICIO%20NACIONAL%20FORESTAL%20Y%20FAUNA%20SILVESTRE%20Y%20EL%20GOBIERNO%20REGIONAL%20DE%20UCAYALI.pdf',gradient:'linear-gradient(150deg,#25596b,#599f69)'},
  {id:6,shortTitle:'Ordenanza N.° 024-2018',title:'Ordenanza Regional N.° 024-2018-GRU-CR',category:'Normativa',badge:'MARCO NORMATIVO',year:'2018',description:'Norma regional que respalda el ordenamiento, estandarización y actualización de la información geoespacial en Ucayali mediante la Infraestructura de Datos Espaciales.',institution:'Gobierno Regional de Ucayali',type:'Ordenanza Regional',scope:'Información geoespacial regional',reference:'N.° 024-2018-GRU-CR',tags:['Ordenanza regional','Estandarización','IDE','Información geoespacial'],previewType:'PDF · Norma regional',url:'https://ider.regionucayali.gob.pe/images/Documentos/04._Ordenanza_Regional_N024-2018-GRU-CR.pdf',gradient:'linear-gradient(150deg,#574f41,#b49b60)'}
];
const $=id=>document.getElementById(id);let selectedId=1,activeFilter='Todos',spread=0,zoom=1,isTurning=false;
const current=()=>documents.find(d=>d.id===selectedId)||documents[0];
function filtered(){const q=$('searchInput').value.toLowerCase().trim();return documents.filter(d=>(activeFilter==='Todos'||d.category===activeFilter)&&(!q||[d.title,d.shortTitle,d.category,d.description,...d.tags].join(' ').toLowerCase().includes(q)))}
function renderList(){const list=filtered();$('resultCount').textContent=list.length;if(list.length&&!list.some(d=>d.id===selectedId))selectedId=list[0].id;$('documentList').innerHTML=list.map(d=>`<button class="document-item ${d.id===selectedId?'active':''}" data-id="${d.id}">${d.cover?`<img class="mini-cover" src="${d.cover}" alt="">`:`<span class="mini-symbol" style="background:${d.gradient}">${d.shortTitle}</span>`}<span><h3>${d.shortTitle}</h3><p>${d.category} · ${d.previewType.split('·')[0]}</p></span><span class="arrow">›</span></button>`).join('')||'<p>No se encontraron documentos.</p>';$('documentList').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selectedId=+b.dataset.id;renderList();renderDetail()})}
function renderDetail(){const d=current();$('coverPreview').innerHTML=d.cover?`<img class="real-cover" src="${d.cover}" alt="Portada de ${d.shortTitle}">`:`<div class="cover-sheet" style="background:${d.gradient}"><div class="cover-art"><div class="cover-brand"><span>GORE UCAYALI</span><span>GeoUcayali</span></div><div class="cover-lines"><h3 class="cover-title">${d.shortTitle}</h3><p class="cover-subtitle">${d.title}</p></div><div class="cover-graphic"></div><div class="cover-footer"><span>${d.category.toUpperCase()}</span><span>${d.year}</span></div></div></div>`;$('previewType').textContent=d.previewType;$('detailCategory').textContent=d.badge;$('detailYear').textContent=d.year;$('detailTitle').textContent=d.title;$('detailDescription').textContent=d.description;$('detailTags').innerHTML=d.tags.map(t=>`<span class="tag">${t}</span>`).join('');$('detailInstitution').textContent=d.institution;$('detailType').textContent=d.type;$('detailScope').textContent=d.scope;$('detailReference').textContent=d.reference;$('sourceLink').href=d.pdf||d.url;$('sourceLink').textContent=d.pdf?'Abrir PDF original':'Fuente original';$('openViewer').textContent=d.pageCount?'Leer como libro →':'Consultar documento →'}
function pagePath(d,n){return `${d.pagesFolder}/${String(n).padStart(3,'0')}.jpg`}
function pageMarkup(d,n,side){if(!n||n>d.pageCount)return '<div class="blank-page"></div>';return `<img class="page-image" src="${pagePath(d,n)}" alt="Página ${n} de ${d.title}"><span class="page-number-chip">${n}</span>`}
function spreadPages(d,s){if(s===0)return [0,1];const left=s*2,right=left+1;return [left,right]}
function renderSpread(){const d=current();const [l,r]=spreadPages(d,spread);$('leftPage').innerHTML=pageMarkup(d,l,'left');$('rightPage').innerHTML=pageMarkup(d,r,'right');if(spread===0)$('pageIndicator').textContent=`Portada · página 1 de ${d.pageCount}`;else $('pageIndicator').textContent=`Páginas ${l}${r<=d.pageCount?'–'+r:''} de ${d.pageCount}`;$('prevPage').disabled=spread===0;$('nextPage').disabled=(r>=d.pageCount);$('pageInput').max=d.pageCount;$('pageInput').value=(spread===0?1:l);preload(d,l-2,l-1,r+1,r+2)}
function preload(d,...nums){nums.filter(n=>n>=1&&n<=d.pageCount).forEach(n=>{const im=new Image();im.src=pagePath(d,n)})}
function turn(dir){if(isTurning)return;const d=current();const maxSpread=Math.ceil(d.pageCount/2);if(dir==='next'&&spread>=maxSpread)return;if(dir==='prev'&&spread<=0)return;isTurning=true;const t=$('turningPage');let imagePage;if(dir==='next'){const [,r]=spreadPages(d,spread);imagePage=r||1;t.style.backgroundImage=`url("${pagePath(d,imagePage)}")`;t.className='turning-page forward'}else{const [l]=spreadPages(d,spread);imagePage=l||1;t.style.backgroundImage=`url("${pagePath(d,imagePage)}")`;t.className='turning-page backward'};setTimeout(()=>{spread+=dir==='next'?1:-1;renderSpread();t.className='turning-page';t.style.backgroundImage='none';isTurning=false},540)}
function openViewer(){const d=current();if(!d.pageCount){window.open(d.url,'_blank','noopener');return}spread=0;zoom=1;applyZoom();$('viewerTitle').textContent=d.title;$('viewerCategory').textContent=d.badge;$('modalSourceLink').href=d.pdf;$('viewerModal').classList.add('open');$('viewerModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';renderSpread()}
function closeViewer(){$('viewerModal').classList.remove('open');$('viewerModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function applyZoom(){$('book').style.setProperty('--zoom',zoom);$('zoomLabel').textContent=Math.round(zoom*100)+'%'}
function gotoPage(){const d=current();let p=parseInt($('pageInput').value,10);if(!p||p<1)p=1;if(p>d.pageCount)p=d.pageCount;spread=p===1?0:Math.floor(p/2);renderSpread()}
$('searchInput').oninput=()=>{renderList();renderDetail()};$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderList();renderDetail()};$('openViewer').onclick=openViewer;$('previewButton').onclick=openViewer;$('nextPage').onclick=()=>turn('next');$('prevPage').onclick=()=>turn('prev');$('zoomIn').onclick=()=>{zoom=Math.min(1.5,zoom+.1);applyZoom()};$('zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.1);applyZoom()};$('goPage').onclick=gotoPage;$('pageInput').onkeydown=e=>{if(e.key==='Enter')gotoPage()};$('fullscreenBtn').onclick=async()=>{const card=$('bookModalCard');if(!document.fullscreenElement){try{await card.requestFullscreen()}catch(e){}}else{document.exitFullscreen()}};document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeViewer);document.onkeydown=e=>{if(!$('viewerModal').classList.contains('open'))return;if(e.key==='Escape'&&!document.fullscreenElement)closeViewer();if(e.key==='ArrowRight')turn('next');if(e.key==='ArrowLeft')turn('prev')};renderList();renderDetail();
